name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install @marp-team/marp-cli

      - name: Generate HTML from Markdown
        run: |
          for file in $(find md/ -type f -name '*.md'); do
            filename=$(basename "$file" .md)
            npx @marp-team/marp-cli@latest "$file" -o "html/${filename}.html"
          done
        shell: /usr/bin/bash -e {0}
      
      - name: Generate index.html
        run: |
          echo "<html><body><h1>Presentations</h1><ul>" > html/index.html
          for file in html/*.html; do
            if [ "$(basename "$file")" != "index.html" ]; then
              filename=$(basename "$file")
              echo "<li><a href=\"$filename\">$(basename "$filename" .html)</a></li>" >> html/index.html
            fi
          done
          echo "</ul></body></html>" >> html/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./html

      